SELECT A.EMP_NO, A.성명, B.PAY_TOT_AMT, A.급여총액 ,  A.기본급, A.*
FROM HSTN03 A JOIN HDF070T B ON A.EMP_NO = B.EMP_NO AND A.PAY_YYMM = B.PAY_YYMM
WHERE B.PAY_TOT_AMT <> A.급여총액

SELEC

--SELECT B.*
--FROM HSTN03 A JOIN HDF070T B ON A.EMP_NO = B.EMP_NO AND A.PAY_YYMM = B.PAY_YYMM
--WHERE B.REAL_PROV_AMT <> A.실발급급여


/*
 보류
 20200001	严虹

*/