--==============================================================
/*
--EXCEL
1. 받은 excel, 데이터만 복사, 값 붙여놓기
2. 계정과목, 전략구매팀, 여행보험팀, 글로벌영업팀, 통합구매팀, 철강팀, 일반무역팀 -> 코드로 바꿔주기 
CLASS_NM 계정과목 
A300 전략구매	
C100 여행보험팀
A108 글로벌영업팀
A106 통합구매팀
B600 철강팀		
B900 일반무역팀	
C200 회사공통
C300 서울사무소


3. 액셀시트 - () 없이 데이터형식 숫자로 변환후 작업
4. 공백제거

BEGIN TRAN
UPDATE BASIC_AFTER_202006
SET CLASS_NM = REPLACE(CLASS_NM,' ','')



SUM_BEBORE_202006
SUM_AFTER_202006
BASIC_BEFORE_202006
BASIC_AFTER_202006

DROP TABLE
 BASIC_AFTER_202006


5. 해외사무소경비 -> 해외지점경비

BEGIN TRAN
UPDATE SUM_BEFORE_202007
SET CLASS_NM = '해외지점경비'
WHERE CLASS_NM = '해외사무소경비'


6. --회사공통 누계서 삭제 (확인 필요)

BEGIN TRAN
UPDATE G_PL_LINE_KO512
SET LOC_AMT = 0
WHERE FISC_YR = '2020'
AND FISC_MNTH = '07'
AND LINE_CD = 'C200'

BEGIN TRAN
UPDATE G_PL_LINE_YEAR_KO512
SET LOC_AMT = 0
WHERE FISC_YR = '2020'
AND FISC_MNTH = '07'
AND LINE_CD = 'C200'


7. 서울사무소 삭제

BEGIN TRAN
DELETE FROM G_PL_LINE_YEAR_KO512
WHERe FISC_YR = '2020'
AND FISC_MNTH = '07'
AND LINE_CD = 'C300'

BEGIN TRAN
DELETE FROM G_PL_LINE_KO512
WHERe FISC_YR = '2020'
AND FISC_MNTH = '07'
AND LINE_CD = 'C300'




--문서 저장시, 
누계 : 배부전 SUM_BEFORE,
         배부후 SUM_AFTER

일반 : 배부전 BASIC_BEFORE
         배부후 BASIC_AFTER



--다 한뒤에 테이블 삭제 
DROP TABLE BASIC_AFTER9
DROP TABLE SUM_BEFORE8
DROP TABLE SUM_AFTER8
DROP TABLE BASIC_BEFORE8


*/
--==============================================================


SUM_BEFORE_202006
SUM_AFTER_202006
BASIC_BEFORE_202006
BASIC_AFTER_202006


UPDATE A 
SET A.BEFORE_AMT = B.C100
FROM G_PL_LINE_KO512 A JOIN BASIC_BEFORE4 B ON REPLACE(A.CLASS_NM,' ','') = B.CLASS_NM
WHERE A.FISC_YR = '2020'
AND A.FISC_MNTH = '07'
AND A.LINE_CD = 'C100'

UPDATE A 
SET A.LOC_AMT = B.C100
FROM G_PL_LINE_KO512 A JOIN BASIC_AFTER4 B ON REPLACE(A.CLASS_NM,' ','') = B.CLASS_NM
WHERE A.FISC_YR = '2020'
AND A.FISC_MNTH = '07'
AND A.LINE_CD = 'C100'


UPDATE A 
SET A.BEFORE_AMT = B.C100
FROM G_PL_LINE_YEAR_KO512 A JOIN SUM_BEFORE4 B ON REPLACE(A.CLASS_NM,' ','') = B.CLASS_NM
WHERE A.FISC_YR = '2020'
AND A.FISC_MNTH = '07'
AND A.LINE_CD = 'C100'

UPDATE A 
SET A.LOC_AMT = B.C100
FROM G_PL_LINE_YEAR_KO512 A JOIN SUM_AFTER12 B ON REPLACE(A.CLASS_NM,' ','') = B.CLASS_NM
WHERE A.FISC_YR = '2020'
AND A.FISC_MNTH = '07'
AND A.LINE_CD = 'C100'



ROLLBACK
COMMIT

-------------------------------
--6. 회사공통 누계서 삭제 (확인 필요)

--SUM_AFTER C200없음 
--C200 BASIC_BEFORE 에 X

SELECT *
FROM G_PL_LINE_KO512
WHERE FISC_YR = '2020'
AND FISC_MNTH = '06'
AND LINE_CD = 'C200'

SELECT *
FROM G_PL_LINE_YEAR_KO512
WHERE FISC_YR = '2020'
AND FISC_MNTH = '06'
AND LINE_CD = 'C200'

BEGIN TRAN
UPDATE G_PL_LINE_KO512
SET LOC_AMT = 0
WHERE FISC_YR = '2020'
AND FISC_MNTH = '07'
AND LINE_CD = 'C200'

BEGIN TRAN
UPDATE G_PL_LINE_YEAR_KO512
SET LOC_AMT = 0
WHERE FISC_YR = '2020'
AND FISC_MNTH = '07'
AND LINE_CD = 'C200'

SELECT *
FROM G_PL_LINE_YEAR_KO512 A
WHERE A.FISC_YR = '2020'
AND A.FISC_MNTH = '05'
AND A.LINE_CD = 'C200'

SELECT A.CLASS_NM, A.BEFORE_AMT , B.C200
FROM G_PL_LINE_KO512 A JOIN BASIC_BEFORE5 B ON A.CLASS_NM = B.CLASS_NM
WHERE A.FISC_YR = '2020'
AND A.FISC_MNTH = '05'
AND A.LINE_CD = 'C200'



------------------------------------------------------
--7. 서울사무소 삭제 
BEGIN TRAN
DELETE FROM G_PL_LINE_YEAR_KO512
WHERe FISC_YR = '2020'
AND FISC_MNTH = '07'
AND LINE_CD = 'C300'

BEGIN TRAN
DELETE FROM G_PL_LINE_KO512
WHERe FISC_YR = '2020'
AND FISC_MNTH = '07'
AND LINE_CD = 'C300'


COMMIT