/*

현금담보 M_DB_DTL.BL_DOC_NO 값 확인 

*/

SELECT * FROM M_DB_DTL A
,(SELECT * FROM OPENQUERY(HSPLATFORM,'   
SELECT D.MAST_DB_NO COL_NO,D.COL_SEQ ,A.BL_NO , A.BL_DOC_NO 
FROM M_BL_HDR_DISTR A, M_BL_DTL_DISTR B,M_LC_DTL_DISTR C,M_COL_D_DISTR D WHERE A.BL_NO=B.BL_NO
AND B.LC_NO=C.LC_NO  AND B.LC_SEQ=C.LC_SEQ AND C.CONT_MGM_NO=D.CONT_MGM_NO')) B
WHERE A.DB_NO=B.COL_NO AND A.SEQ=B.COL_SEQ
AND ISNULL(A.BL_DOC_NO,'')=''


/*
필요시 업데이트
*/

--업데이트 구문
BEGIN TRAN
UPDATE A
SET BL_NO = B.BL_NO
,BL_DOC_NO = B.BL_DOC_NO
,UPDT_DT =GETDATE()
,updt_user_id = 'admin'
FROM M_DB_DTL A INNER JOIN (
SELECT * FROM OPENQUERY(HSPLATFORM,'   SELECT D.MAST_DB_NO COL_NO,D.COL_SEQ ,A.BL_NO , A.BL_DOC_NO FROM M_BL_HDR_DISTR A, M_BL_DTL_DISTR B,M_LC_DTL_DISTR C,M_COL_D_DISTR D WHERE A.BL_NO=B.BL_NO
                  AND B.LC_NO=C.LC_NO  AND B.LC_SEQ=C.LC_SEQ AND C.CONT_MGM_NO=D.CONT_MGM_NO')
) B ON A.DB_NO = B.COL_NO AND A.SEQ = B.COL_SEQ
AND ISNULL(A.BL_DOC_NO, '') = ''
AND DB_NO = ''