 DECLARE		
		
    @GUBUN          VARCHAR(10) = '',      		
    @DN_DTFR  VARCHAR(10) = '2020-06-01',      		
    @DN_DTTO  VARCHAR(10) = '2020-06-31',      		
    @DEPT_CD  VARCHAR(10) = '' ,
	@ITEM_CD VARCHAR(30) = ''	

/*
2019년 마감할때 DN_QTY로 마감해야되는데 DN_REAL_QTY 로 마감된 데이터들이 존재한다.
손익에는 DN_QTY 로 나오고 수불 기초에는 DN_REAL_QTY로 저장되어있는 상태.
2020년에 해당 데이터들이 출고가 완료되면 쿼리에서 출고 수량을 기초수량으로 업데이트 하는 구문이 있다고한다.
이런경우 손익쪽에 DN_REAL_QTY로 보여줘야 하는데 이때 아래의 테이블에 데이터가 들어가있으면 손익 조회 시 수정된 수량으로 보여준다.
*/
--INSERT INTO TEMP_#S4120OA2
	SELECT '202006'	, A.DN_NO,
	A.MVMT_NO, H.IV_TYPE, A.BL_DOC_NO, A.BILL_DT, A.ITEM_CD, DN_REAL_QTY, DN_QTY, Z.DN_TOT_BOX_QTY, Z.GR_BOX_QTY, GETDATE()
				  FROM OPENQUERY(HSPLATFORM,'SELECT * FROM S_BILL_ERP_VIEW') A
				 LEFT OUTER JOIN
					(
						 SELECT MVMT_NO,SUM(DN_BOX_QTY) DN_TOT_BOX_QTY,SUM(DN_QTY) DN_TOT_QTY,GR_QTY,GR_BOX_QTY   
						 FROM OPENQUERY(HSPLATFORM,'SELECT A.DN_DT,A.MVMT_NO,B.QTY GR_QTY,B.BOX_QTY GR_BOX_QTY,A.DN_BOX_QTY,A.DN_QTY FROM M_GR_TO_DN_DISTR A,M_GR_DISTR B WHERE A.MVMT_NO=B.MVMT_NO') B
						 WHERE B.DN_DT<=@DN_DTTO
						 GROUP BY MVMT_NO,GR_QTY,GR_BOX_QTY
					) Z ON A.MVMT_NO=Z.MVMT_NO 
				 INNER JOIN OPENQUERY(HSPLATFORM, 'SELECT DISTINCT MVMT_NO, ITEM_CD, IV_TYPE FROM S_DN_ACCT_ERP_VIEW') H ON A.MVMT_NO = H.MVMT_NO AND A.ITEM_CD = H.ITEM_CD
				 LEFT OUTER JOIN M_GR_ERP_HSPF_IF B ON B.HSPF_MVMT_NO=A.MVMT_NO
				 LEFT OUTER JOIN M_PUR_GOODS_MVMT C ON B.ERP_MVMT_NO=C.MVMT_NO
				 LEFT OUTER JOIN B_ITEM D ON C.ITEM_CD=D.ITEM_CD 
				 LEFT OUTER JOIN B_ITEM_GROUP E ON D.ITEM_GROUP_CD = E.ITEM_GROUP_CD  
				 LEFT OUTER JOIN B_COST_CENTER F ON E.COST_CENTER=F.COST_CD
				 LEFT OUTER JOIN B_COST_CENTER G ON A.COST_CD=G.COST_CD
				 WHERE A.BILL_DT>=@DN_DTFR  AND A.BILL_DT<=@DN_DTTO
--				 AND A.ITEM_CD IN(
--@ITEM_CD
--)
				 and C.ITEM_CD is null	
				  AND A.MVMT_NO LIKE '%PG2019%'		
				  AND A.MVMT_NO NOT IN (
				  SELECT MVMT_NO 
				  FROM TEMP_S4120OA2_2019
				  )	 
ORDER BY BILL_DT

